# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timvw.be" # the base hostname & protocol for your site, e.g. http://example.com
title: "Tim Van Wassenhove's blog"
description: "Tim Van Wassenhove's blog, data architecture, software development, streaming data, fast data, open source software, kafka, spark, kubernetes, docker, parenting" # used by search engines
twitter_username: timvw
github_username:  timvw

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - run.sh
  
