# SITE CONFIGURATION
baseurl: ""
url: "https://timvw.be"
title: "Tim Van Wassenhove's blog" # site's title
description: "Tim Van Wassenhove's blog, data architecture, software development, streaming data, fast data, open source software, kafka, spark, kubernetes, docker, parenting" # used by search engines

exclude: ["Gemfile", "Gemfile.lock", "*.gem", "LICENSE", "README.md", "run.sh"]
