# SITE CONFIGURATION
baseurl: ""
url: "https://timvw.be"
title: "Tim Van Wassenhove's blog" # site's title
description: "Tim Van Wassenhove's blog, data architecture, software development, streaming data, fast data, open source software, kafka, spark, kubernetes, docker, parenting" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Tim Van Wassenhove's blog" # blog's title
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Data Architect, software development, streaming data, fast data, open-source enthusiast, Kafka, Spark, Kubernetes, Docker, Father of two...</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: ""
  
  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "timvw"
  google_plus:
  instagram:
  keybase: timvw
  linkedin: "https://www.linkedin.com/in/timvanwassenhove/" # Full URL""
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "timvw"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "timvw"
  katex: true # Enable if using math markup

  special_page:
    search:
      icon: "search"
      enabled: true
    tags:
      icon: "tags"
      enabled: true

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true


# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
