BaseURL: https://timvw.be/
title: Tim Van Wassenhove
languageCode: en-us
theme: ink
disablePathToLower: true
enableGitInfo: true
relativeURLs: true

outputs:
  home:
  - HTML
  - RSS

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

params:
  subtitle: Passionate geek, interested in Technology. Proud father of two
  social:
    - name: "Twitter"
      icon: "twitter"
      url: "https://twitter.com/timvw"    
    - name: "Github"
      icon: "github"
      url: "https://github.com/timvw"
    - name: "Linkedin"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/timvanwassenhove"
    - name: "RSS"
      icon: "rss"
      url: "https://timvw.be/feed.xml"
  featherIconsCDN: true
  mode: light

googleAnalytics: "UA-2585435-1"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "All posts"
      url: "/post"
      weight: 2
    - name: Tags
      url: "/tags"
      weight: 3

markup:
  highlight:
    style: github