title: Tim Van Wassenhove's blog
languageCode: en-us
theme: clarity
disablePathToLower: true

outputs:
  home:
  - HTML
  - RSS

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

params:
  ga_analytics: UA-2585435-1
  twitter: timvw