title: Tim Van Wassenhove
languageCode: en-us
theme: ink
disablePathToLower: true

outputs:
  home:
  - HTML
  - RSS

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

params:
  social:
    - name: "Twitter"
      icon: "twitter"
      url: "https://twitter.com/timvw"    
    - name: "Github"
      icon: "github"
      url: "https://github.com/timvw"
    - name: "Linkedin"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/timvanwassenhove"
  featherIconsCDN: true
  mode: light


googleAnalytics: "UA-2585435-1"